package com.bizvpm.dps.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "IPersistence", targetNamespace = "http://server.dps.bizvpm.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IPersistence {

	/**
	 * 
	 * @param host
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/getHostAddressRequest", output = "http://server.dps.bizvpm.com/IPersistence/getHostAddressResponse")
	public String getHostAddress(@WebParam(name = "host", partName = "host") String host);

	/**
	 * 
	 * @param taskId
	 */
	@WebMethod
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/removeTaskRequest", output = "http://server.dps.bizvpm.com/IPersistence/removeTaskResponse")
	public void removeTask(@WebParam(name = "taskId", partName = "taskId") String taskId);

	/**
	 * 
	 * @param host
	 * @param task
	 * @param processorTypeId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/createTaskRequest", output = "http://server.dps.bizvpm.com/IPersistence/createTaskResponse")
	public String createTask(@WebParam(name = "host", partName = "host") String host,
			@WebParam(name = "processorTypeId", partName = "processorTypeId") String processorTypeId,
			@WebParam(name = "task", partName = "task") Task task);

	/**
	 * 
	 * @param host
	 * @return returns com.bizvision.dps.service.TaskList
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/getTaskListRequest", output = "http://server.dps.bizvpm.com/IPersistence/getTaskListResponse")
	public TaskList getTaskList(@WebParam(name = "host", partName = "host") String host);

	/**
	 * 
	 * @param manager
	 * @param status
	 */
	@WebMethod
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/updateProcessManagerStatusRequest", output = "http://server.dps.bizvpm.com/IPersistence/updateProcessManagerStatusResponse")
	public void updateProcessManagerStatus(
			@WebParam(name = "manager", partName = "manager") PersistableProcessorManager manager,
			@WebParam(name = "status", partName = "status") int status);

	/**
	 * 
	 * @param status
	 * @return returns com.bizvision.dps.service.ProcessorList
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/getProcessorListRequest", output = "http://server.dps.bizvpm.com/IPersistence/getProcessorListResponse")
	public ProcessorList getProcessorList(@WebParam(name = "status", partName = "status") int status);

	/**
	 * 
	 * @param processorTypeId
	 * @return returns com.bizvision.dps.service.StringList
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/getOnlineProcessManagerRequest", output = "http://server.dps.bizvpm.com/IPersistence/getOnlineProcessManagerResponse")
	public StringList getOnlineProcessManager(
			@WebParam(name = "processorTypeId", partName = "processorTypeId") String processorTypeId);

	/**
	 * 
	 * @param taskId
	 * @param status
	 */
	@WebMethod
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/updateTaskStatusRequest", output = "http://server.dps.bizvpm.com/IPersistence/updateTaskStatusResponse")
	public void updateTaskStatus(
			@WebParam(name = "taskId", partName = "taskId") String taskId,
			@WebParam(name = "result", partName = "result") Result result,
			@WebParam(name = "status", partName = "status") String status);

	/**
	 * 
	 * @param message
	 * @param taskId
	 * @param status
	 */
	@WebMethod
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/updateTaskStatusWithMessageRequest", output = "http://server.dps.bizvpm.com/IPersistence/updateTaskStatusWithMessageResponse")
	public void updateTaskStatusWithMessage(
			@WebParam(name = "taskId", partName = "taskId") String taskId,
			@WebParam(name = "result", partName = "result") Result result,
			@WebParam(name = "status", partName = "status") String status,
			@WebParam(name = "message", partName = "message") String message);

	/**
	 * 
	 * @param taskList
	 */
	@WebMethod
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/removeTaskListRequest", output = "http://server.dps.bizvpm.com/IPersistence/removeTaskListResponse")
	public void removeTaskList(@WebParam(name = "taskList", partName = "taskList") StringList taskList);

	@WebMethod
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/removeTaskListByProcessorTypeIdRequest", output = "http://server.dps.bizvpm.com/IPersistence/removeTaskListByProcessorTypeIdResponse")
	public void removeTaskListByProcessorTypeId(
			@WebParam(name = "processorTypeId", partName = "processorTypeId") String processorTypeId);

	/**
	 * 
	 * @param host
	 * @param processorTypeId
	 * @return returns com.bizvision.dps.service.TaskList
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/getTaskListByProcessorTypeIdRequest", output = "http://server.dps.bizvpm.com/IPersistence/getTaskListByProcessorTypeIdResponse")
	public TaskList getTaskListByProcessorTypeId(@WebParam(name = "host", partName = "host") String host,
			@WebParam(name = "processorTypeId", partName = "processorTypeId") String processorTypeId);

	/**
	 * 
	 * @param status
	 * @param hosts
	 */
	@WebMethod
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/updateProcessManagerStatusByHostsRequest", output = "http://server.dps.bizvpm.com/IPersistence/updateProcessManagerStatusByHostsResponse")
	public void updateProcessManagerStatusByHosts(@WebParam(name = "hosts", partName = "hosts") StringList hosts,
			@WebParam(name = "status", partName = "status") int status);

	/**
	 * 
	 * @param host
	 * @param hostIp
	 * @param hostPort
	 * @param password
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/signinRequest", output = "http://server.dps.bizvpm.com/IPersistence/signinResponse")
	public boolean signin(@WebParam(name = "host", partName = "host") String host,
			@WebParam(name = "password", partName = "password") String password,
			@WebParam(name = "hostIp", partName = "hostIp") String hostIp,
			@WebParam(name = "hostPort", partName = "hostPort") int hostPort);

	/**
	 * 
	 * @param host
	 * @param hostIp
	 * @param hostPort
	 * @param password
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/signupRequest", output = "http://server.dps.bizvpm.com/IPersistence/signupResponse")
	public boolean signup(@WebParam(name = "host", partName = "host") String host,
			@WebParam(name = "password", partName = "password") String password,
			@WebParam(name = "hostIp", partName = "hostIp") String hostIp,
			@WebParam(name = "hostPort", partName = "hostPort") int hostPort);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://server.dps.bizvpm.com/IPersistence/pingRequest", output = "http://server.dps.bizvpm.com/IPersistence/pingResponse")
	public String ping();

}
