
package com.bizvpm.dps.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DPServerService", targetNamespace = "http://server.dps.bizvpm.com/", wsdlLocation = "http://127.0.0.1:8199/dps/server?wsdl")
public class DPServerService
    extends Service
{

    private final static URL DPSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DPSERVERSERVICE_EXCEPTION;
    private final static QName DPSERVERSERVICE_QNAME = new QName("http://server.dps.bizvpm.com/", "DPServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8199/dps/server?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DPSERVERSERVICE_WSDL_LOCATION = url;
        DPSERVERSERVICE_EXCEPTION = e;
    }

    public DPServerService() {
        super(__getWsdlLocation(), DPSERVERSERVICE_QNAME);
    }

    public DPServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DPSERVERSERVICE_QNAME, features);
    }

    public DPServerService(URL wsdlLocation) {
        super(wsdlLocation, DPSERVERSERVICE_QNAME);
    }

    public DPServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DPSERVERSERVICE_QNAME, features);
    }

    public DPServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DPServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DPServer
     */
    @WebEndpoint(name = "DPServerPort")
    public DPServer getDPServerPort() {
        return super.getPort(new QName("http://server.dps.bizvpm.com/", "DPServerPort"), DPServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DPServer
     */
    @WebEndpoint(name = "DPServerPort")
    public DPServer getDPServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.dps.bizvpm.com/", "DPServerPort"), DPServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DPSERVERSERVICE_EXCEPTION!= null) {
            throw DPSERVERSERVICE_EXCEPTION;
        }
        return DPSERVERSERVICE_WSDL_LOCATION;
    }

}
