
package com.bizvpm.dps.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ProcessException", targetNamespace = "http://service.dps.bizvpm.com/")
public class ProcessException
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 8933874561223559662L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProcessFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ProcessException(String message, ProcessFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ProcessException(String message, ProcessFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bizvpm.dps.client.ProcessFault
     */
    public ProcessFault getFaultInfo() {
        return faultInfo;
    }

}
