
package com.bizvpm.dps.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessorManagerService", targetNamespace = "http://service.dps.bizvpm.com/", wsdlLocation = "http://127.0.0.1:26000/processor?wsdl")
public class ProcessorManagerService
    extends Service
{

    private final static URL PROCESSORMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSORMANAGERSERVICE_EXCEPTION;
    private final static QName PROCESSORMANAGERSERVICE_QNAME = new QName("http://service.dps.bizvpm.com/", "ProcessorManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:26000/processor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSORMANAGERSERVICE_WSDL_LOCATION = url;
        PROCESSORMANAGERSERVICE_EXCEPTION = e;
    }

    public ProcessorManagerService() {
        super(__getWsdlLocation(), PROCESSORMANAGERSERVICE_QNAME);
    }

    public ProcessorManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSORMANAGERSERVICE_QNAME, features);
    }

    public ProcessorManagerService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSORMANAGERSERVICE_QNAME);
    }

    public ProcessorManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSORMANAGERSERVICE_QNAME, features);
    }

    public ProcessorManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessorManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IProcessorManager
     */
    @WebEndpoint(name = "ProcessorManagerPort")
    public IProcessorManager getProcessorManagerPort() {
        return super.getPort(new QName("http://service.dps.bizvpm.com/", "ProcessorManagerPort"), IProcessorManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProcessorManager
     */
    @WebEndpoint(name = "ProcessorManagerPort")
    public IProcessorManager getProcessorManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.dps.bizvpm.com/", "ProcessorManagerPort"), IProcessorManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSORMANAGERSERVICE_EXCEPTION!= null) {
            throw PROCESSORMANAGERSERVICE_EXCEPTION;
        }
        return PROCESSORMANAGERSERVICE_WSDL_LOCATION;
    }

}
