
package com.tmt.dps.processor.sms.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BS3WebserviceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BS3WebserviceSoap {


    /**
     * 
     * @param userName
     * @param userPsw
     * @return
     *     returns com.tmt.dps.processor.sms.client.GetBalanceResponse.GetBalanceResult
     */
    @WebMethod(operationName = "GetBalance", action = "http://tempuri.org/GetBalance")
    @WebResult(name = "GetBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBalance", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.GetBalance")
    @ResponseWrapper(localName = "GetBalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.GetBalanceResponse")
    public com.tmt.dps.processor.sms.client.GetBalanceResponse.GetBalanceResult getBalance(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "UserPsw", targetNamespace = "http://tempuri.org/")
        String userPsw);

    /**
     * 
     * @param smsContent
     * @param schTime
     * @param accountInfo
     * @param accountType
     * @param smsMobile
     * @param userName
     * @param userPsw
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.SendSMSResponse")
    public String sendSMS(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "UserPsw", targetNamespace = "http://tempuri.org/")
        String userPsw,
        @WebParam(name = "AccountType", targetNamespace = "http://tempuri.org/")
        String accountType,
        @WebParam(name = "AccountInfo", targetNamespace = "http://tempuri.org/")
        String accountInfo,
        @WebParam(name = "SchTime", targetNamespace = "http://tempuri.org/")
        String schTime,
        @WebParam(name = "SMSMobile", targetNamespace = "http://tempuri.org/")
        String smsMobile,
        @WebParam(name = "SMSContent", targetNamespace = "http://tempuri.org/")
        String smsContent);

    /**
     * 
     * @param userName
     * @param userPsw
     * @return
     *     returns com.tmt.dps.processor.sms.client.ReciveSMSResponse.ReciveSMSResult
     */
    @WebMethod(operationName = "ReciveSMS", action = "http://tempuri.org/ReciveSMS")
    @WebResult(name = "ReciveSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReciveSMS", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.ReciveSMS")
    @ResponseWrapper(localName = "ReciveSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.ReciveSMSResponse")
    public com.tmt.dps.processor.sms.client.ReciveSMSResponse.ReciveSMSResult reciveSMS(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "UserPsw", targetNamespace = "http://tempuri.org/")
        String userPsw);

    /**
     * 
     * @param userName
     * @param userPsw
     * @return
     *     returns com.tmt.dps.processor.sms.client.GetChannelResponse.GetChannelResult
     */
    @WebMethod(operationName = "GetChannel", action = "http://tempuri.org/GetChannel")
    @WebResult(name = "GetChannelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetChannel", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.GetChannel")
    @ResponseWrapper(localName = "GetChannelResponse", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.GetChannelResponse")
    public com.tmt.dps.processor.sms.client.GetChannelResponse.GetChannelResult getChannel(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "UserPsw", targetNamespace = "http://tempuri.org/")
        String userPsw);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "About", action = "http://tempuri.org/About")
    @WebResult(name = "AboutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "About", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.About")
    @ResponseWrapper(localName = "AboutResponse", targetNamespace = "http://tempuri.org/", className = "com.tmt.dps.processor.sms.client.AboutResponse")
    public String about();

}
