
package com.tmt.dps.processor.sms.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BS3Webservice", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://sms2.teg.cn/API/BS3Webservice.asmx?WSDL")
public class BS3Webservice
    extends Service
{

    private final static URL BS3WEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BS3WEBSERVICE_EXCEPTION;
    private final static QName BS3WEBSERVICE_QNAME = new QName("http://tempuri.org/", "BS3Webservice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sms2.teg.cn/API/BS3Webservice.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BS3WEBSERVICE_WSDL_LOCATION = url;
        BS3WEBSERVICE_EXCEPTION = e;
    }

    public BS3Webservice() {
        super(__getWsdlLocation(), BS3WEBSERVICE_QNAME);
    }

    public BS3Webservice(WebServiceFeature... features) {
        super(__getWsdlLocation(), BS3WEBSERVICE_QNAME, features);
    }

    public BS3Webservice(URL wsdlLocation) {
        super(wsdlLocation, BS3WEBSERVICE_QNAME);
    }

    public BS3Webservice(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BS3WEBSERVICE_QNAME, features);
    }

    public BS3Webservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BS3Webservice(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BS3WebserviceSoap
     */
    @WebEndpoint(name = "BS3WebserviceSoap")
    public BS3WebserviceSoap getBS3WebserviceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "BS3WebserviceSoap"), BS3WebserviceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BS3WebserviceSoap
     */
    @WebEndpoint(name = "BS3WebserviceSoap")
    public BS3WebserviceSoap getBS3WebserviceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BS3WebserviceSoap"), BS3WebserviceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BS3WEBSERVICE_EXCEPTION!= null) {
            throw BS3WEBSERVICE_EXCEPTION;
        }
        return BS3WEBSERVICE_WSDL_LOCATION;
    }

}
